### GET ALL CARTS
GET http://localhost:3000/api/cart/guille HTTP/1.1


### POST cart

POST http://localhost:3000/api/cart HTTP/1.1
Content-Type: application/json

{
   "username": "guille",
    "movie": "",
    "theater": "",
    "date": "",
    "time": "",
    "exhibition": null,
    "seats": null,
    "selectedExtras": null
}

### PUT cart
PUT http://localhost:3000/api/cart/guille HTTP/1.1
Content-Type: application/json

{
    "movie": "111",
    "date": "333",
    "time": "444"
}