### GET ALL FUNCIONES
GET http://localhost:3000/api/funciones HTTP/1.1

### POST FUNCIONES
POST http://localhost:3000/api/funciones HTTP/1.1
Content-Type: application/json

{
   "id":"1",
   "movie": "6362e742c2146bd85344ff58",
   "theater":"Tres Cruces",
   "date":"2022-11-30",
   "horario":"21:00",
   "price":100,
   "room":[ "63630d5d932485cc05ee0889" ],
   "seatsunavailable":[]
}