### GET ALL CARTS
GET http://localhost:3000/api/cart/guille HTTP/1.1

### POST cart

POST http://localhost:3000/api/purchase HTTP/1.1
Content-Type: application/json

{
   "username": "admin",
    "qr": "XXXXXX",
    "movie": "Avatar",
    "theater": "Tres Cruces",
    "date": "2022-11-11",
    "time": "19:00"
}

### PUT cart
PUT http://localhost:3000/api/cart/admin HTTP/1.1
Content-Type: application/json

{
    "movie": "222"
}