### GET ALL ROOMS
GET http://localhost:3000/api/rooms HTTP/1.1

### GET ROOMS POR ID
GET http://localhost:3000/api/rooms/1 HTTP/1.1

### POST ROOM
POST http://localhost:3000/api/rooms HTTP/1.1
Content-Type: application/json

{
   "id":"1",
   "seats":[
      {
         "row":1,
         "seat":1,
         "empty":false,
         "available":false
      },
      {
         "row":1,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":1,
         "seat":11,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":1,
         "empty":true,
         "available":false
      },
      {
         "row":2,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":7,
         "empty":true,
         "available":false
      },
      {
         "row":2,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":11,
         "empty":false,
         "available":true
      },
      {
         "row":2,
         "seat":12,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":1,
         "empty":true,
         "available":false
      },
      {
         "row":3,
         "seat":2,
         "empty":true,
         "available":false
      },
      {
         "row":3,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":10,
         "empty":false,
         "available":false
      },
      {
         "row":3,
         "seat":11,
         "empty":false,
         "available":true
      },
      {
         "row":3,
         "seat":12,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":1,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":4,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":1,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":5,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":1,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":6,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":1,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":7,
         "seat":10,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":1,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":2,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":3,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":4,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":5,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":6,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":7,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":8,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":9,
         "empty":false,
         "available":true
      },
      {
         "row":8,
         "seat":10,
         "empty":false,
         "available":true
      }
   ]
}

### PUT ROOMS BY ID
PUT http://localhost:3000/api/rooms/1 HTTP/1.1
Content-Type: application/json

{

}

### DELETE ROOMS BY ID
DELETE http://localhost:3000/api/rooms/1 HTTP/1.1