### GET USERS
GET http://localhost:3000/api/users HTTP/1.1

### GET USERS BY USERNAME
GET http://localhost:3000/api/users/admin HTTP/1.1

### POST USERS
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
   "userid": "1",
   "username": "admin",
   "password": "admin",
}

### PUT USERS BY USERNAME
PUT http://localhost:3000/api/users/admin HTTP/1.1
Content-Type: application/json

{
  "password": "admin"
}

### DELETE USERS BY USERNAME
DELETE http://localhost:3000/api/users/img HTTP/1.1